
- oso_service:
    service_name: mariadb
    project_name: etherpad-ansibleapp
    labels:
      app: etherpad-ansibleapp
      service: mariadb
    ports:
    - name: port-3306
      port: 3306
      targetPort: 3306
    selector:
      app: etherpad-ansibleapp
      service: mariadb
  register: output

- debug: var=output
  when: playbook_debug

- oso_service:
    service_name: etherpad
    project_name: etherpad-ansibleapp
    labels:
      app: etherpad-ansibleapp
      service: etherpad
    ports:
    - name: port-9001
      port: 9001
      targetPort: 9001
    selector:
      app: etherpad-ansibleapp
      service: etherpad
  register: output

- debug: var=output
  when: playbook_debug

- oso_route:
    project_name: etherpad-ansibleapp
    service_port: port-9001
    labels:
      app: etherpad-ansibleapp
      service: etherpad
    route_name: etherpad-9001
    replace: true
    service_name: etherpad
    state: present
  register: output

- debug: var=output
  when: playbook_debug

- oso_deployment:
    project_name: etherpad-ansibleapp
    labels:
      app: etherpad-ansibleapp
      service: mariadb
    deployment_name: mariadb
    containers:
    - securityContext: {}
      name: mariadb
      image: docker.io/ansibleapp/etherpad-ansibleapp-mariadb:latest
      env:
        MARIADB_DATABASE: '{{ database_name }}'
        MARIADB_PASSWORD: '{{ database_password }}'
        MARIADB_ROOT_PASSWORD: '{{ root_password }}'
        MARIADB_USERNAME: '{{ database_user }}'
      args:
      - /usr/bin/dumb-init
      - mysqld
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: mariadb-storage
        readOnly: false
      - mountPath: /var/log/mysql
        name: mariadb-logs
        readOnly: false
      command:
      - /usr/bin/entrypoint.sh
      ports:
      - 3306
    replace: true
    volumes:
    - name: mariadb-storage
      persistentVolumeClaim:
        claimName: mariadb-storage
    - name: mariadb-logs
      persistentVolumeClaim:
        claimName: mariadb-logs
  register: output

- debug: var=output
  when: playbook_debug

- oso_deployment:
    project_name: etherpad-ansibleapp
    labels:
      app: etherpad-ansibleapp
      service: etherpad
    deployment_name: etherpad
    containers:
    - securityContext: {}
      name: etherpad
      image: docker.io/ansibleapp/etherpad-ansibleapp-etherpad:latest
      env:
        ADMIN_PASSWORD: '{{ application_password }}'
        DATABASE_HOST: '{{ database_host }}'
        DATABASE_NAME: '{{ database_name }}'
        DATABASE_PASSWORD: '{{ database_password }}'
        DATABASE_USER: '{{ database_user }}'
        SESSION_KEY: '{{ session_key if session_key is defined else (99999 | random
          | to_uuid) }}'
      args:
      - /opt/etherpad-lite/bin/run.sh
      command:
      - /usr/bin/entrypoint.sh
      ports:
      - 9001
    replace: true
  register: output

- debug: var=output
  when: playbook_debug

- oso_pvc:
    state: present
    project_name: etherpad-ansibleapp
    name: mariadb-storage
    access_modes:
    - ReadWriteOnce
  register: output

- debug: var=output
  when: playbook_debug

- oso_pvc:
    state: present
    project_name: etherpad-ansibleapp
    name: mariadb-logs
    access_modes:
    - ReadWriteOnce
  register: output

- debug: var=output
  when: playbook_debug
