- name: oc login
  shell: "oc login {{ openshift_target }} -u '{{ openshift_user }}' -p '{{ openshift_pass }}' --insecure-skip-tls-verify=true"

- oso_pvc:
    state: present
    project_name: "{{ namespace }}"
    name:  mariadb-{{ item }}-data
    access_modes:
    - ReadWriteOnce
  register: output
  with_sequence: count={{ cluster_size }}

- debug: var=output
  when: playbook_debug

- name: create boostrap job definition
  template:
    src: templates/bootstrap-job.j2
    dest: /tmp/bootstrap-job.yml

- name: create bootstrap job
  shell: "oc -n {{ namespace }} create -f bootstrap-job.yml"
  args:
    chdir: /tmp

- name: wait for boostrap to complete
  shell: "oc -n {{ namespace }} get pods | grep mariadb-bootstrap"
  register: job_result
  until: "'Completed' in job_result.stdout"
  retries: 24
  delay: 5

- oso_service:
    ports:
    - name: port-3306
      port: 3306
      targetPort: 3306
    - name: port-4567
      port: 4567
      targetPort: 4567
    - name: port-4567-udp
      port: 4567
      protocol: UDP
      targetPort: 4567
    - name: port-4444
      port: 4444
      targetPort: 4444
    - name: port-4568
      port: 4568
      targetPort: 4568
    service_name: mariadb-{{ item }}
    selector:
      app: galera-ansibleapp
      service: mariadb-{{ item }}
    project_name: "{{ namespace }}"
    labels:
      app: galera-ansibleapp
      service: mariadb-{{ item }}
  register: output
  with_sequence: count={{ cluster_size }}

- debug: var=output
  when: playbook_debug

- oso_deployment:
    deployment_name: mariadb-1
    replace: true
    containers:
    - securityContext: {}
      name: mariadb-1
      image: docker.io/jmontleon/centos-7-galera-mariadb-10:latest
      workingDir: /
      args:
      - /usr/local/bin/run.sh
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: mariadb-1-data
        readOnly: false
      env:
        MARIADB_DATABASE: '{{ mariadb_database }}'
        MARIADB_PASSWORD: '{{ mariadb_password }}'
        MARIADB_ROOT_PASSWORD: '{{ mariadb_root_password }}'
        MARIADB_USERNAME: '{{ mariadb_username }}'
        WSREP_BOOTSTRAP: --wsrep-new-cluster
        WSREP_CLUSTER_ADDRESSES: mariadb-1,mariadb-2,mariadb-3
        WSREP_NODE_NAME: mariadb-1
      ports:
      - 3306
      - 4567
      - 4444
      - 4568
    project_name: "{{ namespace }}"
    labels:
      app: galera-ansibleapp
      service: mariadb-1
    volumes:
    - name: mariadb-1-data
      persistentVolumeClaim:
        claimName: mariadb-1-data
  register: output

- debug: var=output
  when: playbook_debug

- oso_deployment:
    deployment_name: mariadb-{{ item }}
    replace: true
    containers:
    - securityContext: {}
      name: mariadb-{{ item }}
      image: docker.io/jmontleon/centos-7-galera-mariadb-10:latest
      workingDir: /
      args:
      - /usr/local/bin/run.sh
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: mariadb-{{ item }}-data
        readOnly: false
      env:
        MARIADB_DATABASE: '{{ mariadb_database }}'
        MARIADB_PASSWORD: '{{ mariadb_password }}'
        MARIADB_ROOT_PASSWORD: '{{ mariadb_root_password }}'
        MARIADB_USERNAME: '{{ mariadb_username }}'
        WSREP_CLUSTER_ADDRESSES: mariadb-1,mariadb-2,mariadb-3
        WSREP_NODE_NAME: mariadb-{{ item }}
      ports:
      - 3306
      - 4567
      - 4444
      - 4568
    project_name: "{{ namespace }}"
    labels:
      app: galera-ansibleapp
      service: mariadb-{{ item }}
    volumes:
    - name: mariadb-{{ item }}-data
      persistentVolumeClaim:
        claimName: mariadb-{{ item }}-data
  register: output
  with_sequence: start=2 end={{ cluster_size }}

- debug: var=output
  when: playbook_debug
